# Generated by Django 4.2.3 on 2023-07-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
