# Generated by Django 4.2.3 on 2023-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0005_advertisement_cative_to_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date_of_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='important',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
