# Generated by Django 4.2.3 on 2023-08-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0006_advertisement_date_of_end_advertisement_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='cative_to_see',
            new_name='active_to_see',
        ),
    ]
