# Generated by Django 4.2.3 on 2023-08-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0008_advertisement_date_of_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='important',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
