# Generated by Django 4.2.3 on 2023-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0011_alter_advertisement_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='important_group',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
