# Generated by Django 4.2.3 on 2023-08-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paln',
            new_name='plan',
        ),
    ]
