# Generated by Django 4.2.3 on 2023-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use',
            field=models.BooleanField(default=False, verbose_name='using chat'),
        ),
    ]
